<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>DskIntroPlayer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediaBrowser.Server.Core" Version="4.8.0.80" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\configPage.html" />
  </ItemGroup>

</Project>
